import Head from "next/head";
import Image from "next/image";

import Logo from "public/code-platoon-logo-black.png";
import { useEffect, useState } from "react";

const HomePage = () => {
  const [studentData, setStudentData] = useState<{}>({});

  useEffect(() => {
    // This will run only on init render
    getStudentData();
  }, []);

  const getStudentData = async () => {
    const response = await fetch("");
    const data = await response.json();

    setStudentData(data);
  };

  return (
    <>
      <Head>
        <title>The Tango Roulette</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex items-center bg-primary-orange text-center text-xl p-4 text-primary-white drop-shadow-xl">
        <Image src={Logo} alt="code platoon logo" className="w-32" />
        <h1 className="tracking-wider">THE TANGO ROULETTE</h1>
      </header>
      <main className="w-screen h-screen bg-primary-teal flex items-center justify-center font-lato">
        <section className="bg-shades-300 w-10/12 py-20 rounded-xl drop-shadow-xl max-w-xl flex flex-col items-center justify-center gap-10 -translate-y-[30%]">
          <h2 className="text-2xl">Student Name</h2>
          <button className="bg-primary-orange py-2 px-4 rounded-lg text-2xl">
            Roll it
          </button>
        </section>
      </main>
    </>
  );
};

export default HomePage;
