# Generated by Django 4.1.7 on 2023-02-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangoRouletteBackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isRemote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='num_times_chosen',
            field=models.IntegerField(default=0),
        ),
    ]
