export const dummy_data = [
  {
    id: 1,
    firstName: "Leo",
    lastName: "Penrose",
    isRemote: false,
    timesGone: 0,
  },
  {
    id: 2,
    firstName: "Mason",
    lastName: "Dubelbeis",
    isRemote: true,
    timesGone: 0,
  },
  {
    id: 3,
    firstName: "Alexander",
    lastName: "Mills",
    isRemote: false,
    timesGone: 0,
  },
  {
    id: 4,
    firstName: "Angel",
    lastName: "Martinez",
    isRemote: false,
    timesGone: 0,
  },
  {
    id: 6,
    firstName: "Johnny",
    lastName: "Ventura",
    isRemote: false,
    timesGone: 0,
  },
  {
    id: 7,
    firstName: "Danozaur",
    lastName: "Danozaur",
    isRemote: false,
    timesGone: 0,
  },
  {
    id: 8,
    firstName: "Joshua",
    lastName: "Parina",
    isRemote: false,
    timesGone: 0,
  },
  {
    id: 9,
    firstName: "Shaquille",
    lastName: "Cruz",
    isRemote: false,
    timesGone: 0,
  },
  {
    id: 10,
    firstName: "Terrence",
    lastName: "Doyle",
    isRemote: false,
    timesGone: 0,
  },
  {
    id: 11,
    firstName: "Brandon",
    lastName: "Bowland",
    isRemote: true,
    timesGone: 0,
  },
  {
    id: 12,
    firstName: "Brant",
    lastName: "Tremont",
    isRemote: true,
    timesGone: 0,
  },
  {
    id: 13,
    firstName: "Chayse",
    lastName: "Stiver",
    isRemote: true,
    timesGone: 0,
  },
  {
    id: 14,
    firstName: "Chris",
    lastName: "Makin",
    isRemote: true,
    timesGone: 0,
  },
  {
    id: 15,
    firstName: "Dale",
    lastName: "Herman",
    isRemote: false,
    timesGone: 0,
  },
  {
    id: 16,
    firstName: "Dalton",
    lastName: "Daly",
    isRemote: false,
    timesGone: 0,
  },
  {
    id: 17,
    firstName: "Daniel",
    lastName: "Erb",
    isRemote: true,
    timesGone: 0,
  },
  {
    id: 18,
    firstName: "Darren",
    lastName: "Berg",
    isRemote: true,
    timesGone: 0,
  },
  {
    id: 19,
    firstName: "David",
    lastName: "Hichens",
    isRemote: true,
    timesGone: 0,
  },
  {
    id: 20,
    firstName: "Derrick",
    lastName: "Sanchez",
    isRemote: false,
    timesGone: 0,
  },
  {
    id: 21,
    firstName: "Andrew",
    lastName: "Washko",
    isRemote: true,
    timesGone: 0,
  },
  {
    id: 22,
    firstName: "Chris",
    lastName: "Dzikowski",
    isRemote: false,
    timesGone: 0,
  },
  {
    id: 23,
    firstName: "Hosung",
    lastName: "Lee",
    isRemote: true,
    timesGone: 0,
  },
  {
    id: 24,
    firstName: "James",
    lastName: "York",
    isRemote: true,
    timesGone: 0,
  },
  {
    id: 25,
    firstName: "Javier",
    lastName: "P.",
    isRemote: true,
    timesGone: 0,
  },
  {
    id: 26,
    firstName: "Jeremy",
    lastName: "Cuneo",
    isRemote: true,
    timesGone: 0,
  },
  {
    id: 27,
    firstName: "Jody",
    lastName: "Hamberry",
    isRemote: true,
    timesGone: 0,
  },
  {
    id: 28,
    firstName: "Jose",
    lastName: "Delgado",
    isRemote: true,
    timesGone: 0,
  },
  {
    id: 29,
    firstName: "Joshua",
    lastName: "Boulard",
    isRemote: true,
    timesGone: 0,
  },
  {
    id: 30,
    firstName: "Joshua",
    lastName: "Brewer",
    isRemote: true,
    timesGone: 0,
  },
  {
    id: 31,
    firstName: "Julie",
    lastName: "Chen",
    isRemote: true,
    timesGone: 0,
  },
  {
    id: 32,
    firstName: "Marcus",
    lastName: "Gibson",
    isRemote: true,
    timesGone: 0,
  },
  {
    id: 33,
    firstName: "Michael",
    lastName: "Bridges",
    isRemote: true,
    timesGone: 0,
  },
  {
    id: 34,
    firstName: "Michael",
    lastName: "Jenkins",
    isRemote: true,
    timesGone: 0,
  },
  {
    id: 35,
    firstName: "Mickey",
    lastName: "Shoenberger",
    isRemote: true,
    timesGone: 0,
  },
  {
    id: 36,
    firstName: "Nick",
    lastName: "Lukey",
    isRemote: true,
    timesGone: 0,
  },
  {
    id: 37,
    firstName: "Olean",
    lastName: "Reva",
    isRemote: true,
    timesGone: 0,
  },
  {
    id: 38,
    firstName: "Rob",
    lastName: "Haenszel",
    isRemote: true,
    timesGone: 0,
  },
  {
    id: 40,
    firstName: "Steve",
    lastName: "An",
    isRemote: false,
    timesGone: 0,
  },
  {
    id: 41,
    firstName: "Will",
    lastName: "Minshall",
    isRemote: true,
    timesGone: 0,
  },
  {
    id: 42,
    firstName: "Yen",
    lastName: "Pham",
    isRemote: true,
    timesGone: 0,
  },
  {
    id: 43,
    firstName: "Yiran",
    lastName: "Fitzpatrick",
    isRemote: true,
    timesGone: 0,
  },
];
